CREATE DATABASE IF NOT EXISTS login;

CREATE OR REPLACE TABLE users (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    `username` VARCHAR(50) NOT NULL,
    `email` VARCHAR(100) UNIQUE NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `levelAccess` INT NOT NULL DEFAULT 0
);